name: fetch-new-lecture-plan

on:
  workflow_dispatch:
  schedule:
    - cron: "0 4 * * 1"
jobs:
  fetch-new-plan:
      runs-on: ubuntu-latest
      steps:
        - name: Start Fetching of Latest Lecture Plan
          shell: bash
          env:
            TOKEN: ${{secrets.API_KEY}}
            NOT_SECRET: ${{secrets.THIS_CAN_SHOW}}
          run: |
            echo '$NOT_SECRET'
# curl -H 'Authentication: $TOKEN' https://better-room-fino-deq3n.ondigitalocean.app/updateRooms
